// @refresh reload
import "./root.css";
import "./fonts.css";
import { Suspense } from "solid-js";
import {
  Body,
  ErrorBoundary,
  FileRoutes,
  Head,
  Html,
  Meta,
  Routes,
  Scripts,
  Title,
  Link,
} from "solid-start";
import IconMenu from "./components/icon-menu";
import WidthConstraint from "./components/width-constraint";

export default function Root() {
  return (
    <Html lang="en" class="dark">
      <Head>
        <Title>MhLoadout</Title>
        <Meta charset="utf-8" />
        <Meta name="viewport" content="width=device-width, initial-scale=1" />
        <Meta name="description" content="Generated by create-jd-app" />
        <Link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="border-t-4 border-t-red-600 md:border-t-orange-500 lg:border-t-amber-400 xl:border-t-green-400 2xl:border-t-cyan-300" />
      <WidthConstraint class="flex justify-end">
        <IconMenu />
      </WidthConstraint>
      <Body class="bg-gray-50 text-gray-800 dark:bg-gray-900 dark:text-gray-50">
        <Suspense>
          <ErrorBoundary>
            <Routes>
              <FileRoutes />
            </Routes>
          </ErrorBoundary>
        </Suspense>
        <Scripts />
      </Body>
    </Html>
  );
}
